name: CI

on:
  push:
    branches:
      - main
jobs:
  lint-and-test:
    name: Lint and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      # Enable Corepack for Yarn 4.x
      - name: Enable Corepack
        run: corepack enable
        shell: bash

      # Install Yarn 4.x
      - name: Install Yarn 4.x
        run: corepack prepare yarn@stable --activate
        shell: bash

      # Install dependencies
      - name: Install dependencies
        run: yarn install
        shell: bash

      - name: Run tests
        run: yarn run test:ci
        shell: bash
